import { StyleSheet } from 'react-native';

export const PRIMARY_BLUE = '#1A237E';
export const SUCCESS_GREEN = '#388E3C';

export const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: PRIMARY_BLUE,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerSubtitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 14,
    textTransform: 'lowercase',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  headerTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 2,
  },
  headerHistoryBtn: {
    backgroundColor: 'white',
    height: 40,
    width: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  container: { flex: 1 }, 
  scrollContainer: { padding: 15 },
  card: { backgroundColor: 'white', borderRadius: 12, padding: 18, marginBottom: 15, elevation: 3 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 12 },
  smallCheckBtn: { width: 45, height: 45, justifyContent: 'center', alignItems: 'center', marginLeft: 5 },
  clearBtn: { width: 45, height: 45, justifyContent: 'center', alignItems: 'center', marginLeft: 5, backgroundColor: '#FFEBEE', borderRadius: 10, borderWidth: 1, borderColor: '#FFCDD2' },
  errorBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFEBEE', borderStyle: 'dashed', borderWidth: 1.5, borderColor: '#D32F2F', borderRadius: 10, padding: 10, marginTop: 8 },
  errorBoxText: { color: '#D32F2F', fontSize: 13, fontWeight: '600', flex: 1 },
  compactCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12, backgroundColor: '#E8EAF6', borderRadius: 12 },
  compactContent: { flexDirection: 'row', alignItems: 'center' },
  compactText: { marginLeft: 8, fontSize: 14, color: '#1A237E' },
  editButton: { padding: 4, backgroundColor: '#FFF', borderRadius: 6, borderWidth: 1, borderColor: '#C5CAE9' },
  choiceContainer: { flexDirection: 'row', justifyContent: 'space-between' },
  choiceBtn: { flex: 1, flexDirection: 'row', backgroundColor: '#F0F2F5', padding: 12, borderRadius: 10, justifyContent: 'center', marginHorizontal: 5 },
  choiceBtnActive: { backgroundColor: PRIMARY_BLUE },
  choiceText: { marginLeft: 8, fontWeight: '600' },
  choiceTextActive: { color: 'white' },
  pboInputGroup: { flexDirection: 'row', alignItems: 'center' },
  prefixBadge: { backgroundColor: '#E8F5E9', paddingHorizontal: 10, height: 45, borderRadius: 10, justifyContent: 'center', borderWidth: 1, borderColor: '#388E3C' },
  prefixText: { color: '#388E3C', fontWeight: 'bold' },
  separator: { fontSize: 18, fontWeight: 'bold', paddingHorizontal: 3 },
  styledInput: { backgroundColor: '#F0F2F5', height: 45, borderRadius: 10 },
  pboNumberContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F0F2F5', height: 45, borderRadius: 10, paddingHorizontal: 8 },
  pboPrefixText: { fontWeight: 'bold', color: '#666', fontSize: 13 },
  warningCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF8E1', borderWidth: 1, borderColor: '#d2850a', borderRadius: 12, padding: 18, marginBottom: 15 },
  warningIcon: { marginRight: 12 },
  warningText: { flex: 1, color: '#d2850a' },
  inputWrapper: { backgroundColor: '#F0F2F5', borderRadius: 10, paddingHorizontal: 10, height: 45, marginBottom: 10, borderWidth: 1, borderColor: 'transparent' },
  disabledInput: { backgroundColor: '#E0E0E0', color: '#9E9E9E' }, 
  inputField: { flex: 1, height: '100%' },
  inputFieldActive: { borderColor: PRIMARY_BLUE, borderWidth: 1.5 },
  inputWrapperActive: { borderColor: PRIMARY_BLUE, borderWidth: 1.5 },
  activeInput: { borderColor: PRIMARY_BLUE, backgroundColor: '#FFFFFF', shadowColor: PRIMARY_BLUE, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 5, elevation: 5 },
  checkContainer: { flexDirection: 'row', alignItems: 'center' },
  submitBtn: { backgroundColor: PRIMARY_BLUE, flexDirection: 'row', height: 50, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginTop: 15 },
  submitBtnDisabled: { backgroundColor: '#BDBDBD' },
  submitBtnText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  submitHint: { textAlign: 'center', fontSize: 12, color: '#999', marginTop: 8, fontStyle: 'italic' },
  dashedCard: { borderWidth: 2, borderColor: '#388E3C', borderStyle: 'dashed', borderRadius: 12, padding: 15, marginBottom: 15, flexDirection: 'row', alignItems: 'center', backgroundColor: '#F1F8E9' },
  profileIconContainer: { marginRight: 15 },
  infoContent: { flex: 1 },
  clientLabel: { fontSize: 16, fontWeight: 'bold', color: '#1B5E20' },
  clientDetail: { fontSize: 13, color: '#4E342E', marginTop: 2 },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginTop: 3 },
  photoRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, marginBottom: 10 },
  photoContainer: { flex: 1, marginHorizontal: 4 },
  photoLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 6 },
  photoDashedBox: { height: 120, borderWidth: 1.5, borderColor: '#9E9E9E', borderStyle: 'dashed', borderRadius: 10, backgroundColor: '#F0F2F5', overflow: 'hidden' },
  photoPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  photoPlaceholderText: { fontSize: 12, color: '#757575', marginTop: 4 },
  photoPreviewContainer: { flex: 1, position: 'relative' },
  photoImage: { width: '100%', height: '100%' },
  photoActions: { position: 'absolute', bottom: 5, right: 5, flexDirection: 'row' },
  photoActionBtn: { width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginLeft: 6, elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.22, shadowRadius: 2.22 },
});