import { StyleSheet, Platform } from 'react-native';

export const PRIMARY_BLUE = '#1A237E';

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#F3F4F6' // Remplacement de tw`bg-gray-100`
  },
  headerContainer: {
    backgroundColor: PRIMARY_BLUE,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 40 : 40,
    paddingBottom: 20,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    marginBottom: 15,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerSubtitle: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  headerTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 2,
  },
  headerFilterText: {
    color: '#E8EAF6',
    fontSize: 12,
    marginTop: 4,
    fontStyle: 'italic',
  },
  filterButton: {
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  mainSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    marginHorizontal: 15,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  mainSearchInput: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    padding: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PRIMARY_BLUE,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    padding: 0,
  },
  dropdownItem: { 
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14, 
    borderBottomWidth: 1, 
    borderBottomColor: '#f3f4f6' 
  },
  itemText: { fontSize: 15, color: '#333' },
  itemTextActive: { fontSize: 15, color: PRIMARY_BLUE, fontWeight: 'bold' },
  emptyText: { textAlign: 'center', color: '#888', marginVertical: 15, fontSize: 14 },
  pboCard: { flexDirection: 'row', backgroundColor: 'white', marginHorizontal: 15, marginVertical: 6, padding: 15, borderRadius: 12, elevation: 2, alignItems: 'center' },
  iconContainer: { width: 50, height: 50, borderRadius: 8, backgroundColor: '#f0f9f7', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  pboContent: { flex: 1 },
  pboHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  pboTitle: { fontSize: 15, fontWeight: 'bold', color: '#333', flex: 1, flexShrink: 1 },
  pboDate: { fontSize: 10, color: '#888' },
  pboLoc: { fontSize: 13, color: PRIMARY_BLUE, marginVertical: 2, fontWeight: '500' },
  pboFooter: { flexDirection: 'row', marginTop: 5 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 5, marginRight: 10 },
  badgeText: { fontSize: 10, fontWeight: 'bold' },
  fab: { position: 'absolute', bottom: 25, right: 25, backgroundColor: PRIMARY_BLUE, width: 65, height: 65, borderRadius: 32.5, justifyContent: 'center', alignItems: 'center', elevation: 8 },
  fabMap: { position: 'absolute', bottom: 105, right: 25, backgroundColor: PRIMARY_BLUE, width: 65, height: 65, borderRadius: 32.5, justifyContent: 'center', alignItems: 'center', elevation: 8 }
});